export interface ErrorResponse {
  code: ErroCode;
  message: string;
}

export enum ErroCode {
  MISSING = 'MISSING',
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
  REQUEST_VALIDATION_FAILED = 'REQUEST_VALIDATION_FAILED',
  AUTHENTICATION_REQUIRED = 'AUTHENTICATION_REQUIRED',
  AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED',
  REGISTRATION_FAILED = 'REGISTRATION_FAILED',
  OPERATION_FORBIDDEN = 'OPERATION_FORBIDDEN',
  OPERATION_FAILED = 'OPERATION_FAILED',
  PROFILE_UPDATE_FAILED = 'PROFILE_UPDATE_FAILED',
  CLUB_NAME_ALREADY_TAKEN = 'CLUB_NAME_ALREADY_TAKEN',
  DELETE_USER_FAILED = 'DELETE_USER_FAILED',
  MEMBER_ALREADY_EXISTS = 'MEMBER_ALREADY_EXISTS',
  USER_NOT_A_MEMBER_OF_THE_CLUB = 'USER_NOT_A_MEMBER_OF_THE_CLUB',
  OWNER_CANNOT_LEAVE_CLUB = 'OWNER_CANNOT_LEAVE_CLUB',
  BOOK_ALREADY_EXISTS = 'BOOK_ALREADY_EXISTS'
}
